\documentclass{article}

\begin{document}
\begin{center}
\textbf{\Large{Digital Assignment - 2}}
\newline
Reg. No. : 24MDT0179\\
Name : Bosamiya Gauravkumar \\
Slot : L33 + 34 \\
Course Title : Statistical Inference LAB\\
Course Details: PMDs503P \\

\end{center}

<<>>==


#Q1 

# H0 : mu >= 14
# H1 : mu < 14

library("BSDA")

r1 <-zsum.test(mean.x = 13.5, sigma.x = 3, n.x = 60, mu=14, 
               alternative="less", conf.level = 1-0.05)

r2 <- zsum.test(mean.x = 13.5, sigma.x = 3, n.x = 60, mu=14,
                alternative="less", conf.level = 1-0.01)

cat("z value : ",r1$statistic, "\n")
cat("p value for alpha=0.05 :", r1$p.value, "\n")
cat("p value for alpha=0.01 :",r2$p.value, "\n")

if(r1$p.value < 0.05)
{
  print("alpha=0.05, reject null hypothesis")
}else{
  print("alpha=0.05, fail to reject null hypothesis")
}

if(r2$p.value < 0.01)
{
  print("alpha=0.01, reject null hypothesis")
}else{
  print("alpha=0.01, fail to reject null hypothesis")
}


@

\newpage

<<>>==

# Q2

# H0 : mean1 > = mean2
# H1 : mean1 < mean2

result_1 <- zsum.test(mean.x = 63.5, sigma.x = 5.4, n.x = 45,
                    mean.y = 66.2, sigma.y = 5.8, n.y = 60,
                    alternative = "less", mu = 0, conf.level = 0.95)

result_2 <- zsum.test(mean.x = 63.5, sigma.x = 5.4, n.x = 45,
                    mean.y = 66.2, sigma.y = 5.8, n.y = 60,
                    alternative = "less", mu = 0, conf.level = 0.99)

cat("z value : ",result_1$statistic, "\n")
cat("p value for alpha=0.05 :", result_1$p.value, "\n")
cat("p value for alpha=0.01 :",result_2$p.value, "\n")

if(result_1$p.value < 0.05)
{
  print("alpha=0.05, reject null hypothesis")
}else{
  print("alpha=0.05, fail to reject null hypothesis")
}

if(result_2$p.value < 0.01)
{
  print("alpha=0.01, reject null hypothesis")
}else{
  print("alpha=0.01, fail to reject null hypothesis")
}


@

\newpage

<<>>==

# Q3

# H0 : mean1 = mean2
# H1 : mean1 != mean2

n_a <- 190
n_b <- 65
c_a <- 100
c_b <- 55

p_a <- c_a / n_a
p_b <- c_b / n_b

result <- prop.test(x = c(c_a, c_b), n=c(n_a, n_b), alternative = "two.sided", correct = FALSE)

cat("z value : ",sqrt(result$statistic), "\n")
cat("p value :", result$p.value, "\n")

if(result$p.value < 0.05)
{
  print("alpha=0.05, reject null hypothesis")
}else{
  print("alpha=0.05, fail to reject null hypothesis")
}

if(result$p.value < 0.01)
{
  print("alpha=0.01, reject null hypothesis")
}else{
  print("alpha=0.01, fail to reject null hypothesis")
}
@

<<>>==

# Q4
# H0: mean <= 0.65
# H1: mean > 0.65

n <- 600
f <- 414
p_0 <- 0.65

p_h <- f/n

r_1 <- prop.test(x=f,n=n, p=p_0,
                 alternative = 'greater', correct =  FALSE)

cat("z value : ",sqrt(r_1$statistic), "\n")
cat("p value :", r_1$p.value, "\n")

if(r_1$p.value < 0.05)
{
  print("alpha=0.05, reject null hypothesis")
}else{
  print("alpha=0.05, fail to reject null hypothesis")
}

if(r_1$p.value < 0.01)
{
  print("alpha=0.01, reject null hypothesis")
}else{
  print("alpha=0.01, fail to reject null hypothesis")
}
@
\end{document} 